services:
    sales-app:
        build: .
        container_name: sales-app
        entrypoint: dockerize -template ./.docker/app/.env.template:.env sh -c "npm install && npm run dev --host"
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
        environment:
            - API_ENDPOINT=http://localhost:8000
            - API_TOKEN=1f2d4e8b9c3a7f615d2e4b1a6c9d8f3e
            - APP_DEBUG=true
        networks:
            - tray-network

networks:
    tray-network:
